// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateFramework.Infastructure.Data;

#nullable disable

namespace TemplateFramework.Infastructure.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20250603041748_db5")]
    partial class db5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TemplateFramework.Domain.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2024, 12, 23, 14, 42, 59, 678, DateTimeKind.Local).AddTicks(8355),
                            Description = "Accusantium nihil occaecati accusantium inventore tenetur molestias.",
                            Name = "Licensed Steel Hat",
                            Price = 968.46m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 7, 42, 932, DateTimeKind.Local).AddTicks(3459)
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2025, 4, 24, 7, 14, 45, 730, DateTimeKind.Local).AddTicks(8334),
                            Description = "A est modi provident occaecati.",
                            Name = "Small Concrete Pants",
                            Price = 652.02m,
                            UpdatedAt = new DateTime(2025, 6, 3, 11, 4, 57, 851, DateTimeKind.Local).AddTicks(5249)
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(2025, 4, 23, 0, 44, 22, 424, DateTimeKind.Local).AddTicks(1094),
                            Description = "Delectus corrupti ut.",
                            Name = "Sleek Plastic Shirt",
                            Price = 543.79m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 10, 18, 240, DateTimeKind.Local).AddTicks(6238)
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(2024, 8, 2, 17, 1, 19, 2, DateTimeKind.Local).AddTicks(7439),
                            Description = "Reprehenderit nam facilis blanditiis.",
                            Name = "Handmade Metal Soap",
                            Price = 445.29m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 45, 32, 595, DateTimeKind.Local).AddTicks(290)
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(2025, 1, 2, 10, 19, 13, 537, DateTimeKind.Local).AddTicks(4601),
                            Description = "Asperiores officia exercitationem repudiandae reprehenderit tenetur deserunt.",
                            Name = "Unbranded Soft Pizza",
                            Price = 918.71m,
                            UpdatedAt = new DateTime(2025, 6, 3, 4, 28, 29, 869, DateTimeKind.Local).AddTicks(8238)
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTime(2025, 3, 27, 22, 7, 44, 191, DateTimeKind.Local).AddTicks(7710),
                            Description = "Quos occaecati et ut asperiores et tempore.",
                            Name = "Rustic Frozen Sausages",
                            Price = 596.92m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 36, 58, 777, DateTimeKind.Local).AddTicks(5161)
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTime(2025, 5, 8, 20, 44, 6, 511, DateTimeKind.Local).AddTicks(1835),
                            Description = "Architecto quisquam quo illum doloribus quaerat voluptatem quibusdam provident autem.",
                            Name = "Handcrafted Wooden Chair",
                            Price = 923.33m,
                            UpdatedAt = new DateTime(2025, 6, 3, 7, 37, 18, 633, DateTimeKind.Local).AddTicks(8226)
                        },
                        new
                        {
                            Id = -8,
                            CreatedAt = new DateTime(2025, 1, 14, 8, 28, 1, 531, DateTimeKind.Local).AddTicks(5287),
                            Description = "Et cupiditate eveniet id.",
                            Name = "Practical Fresh Towels",
                            Price = 120.48m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 44, 20, 758, DateTimeKind.Local).AddTicks(2741)
                        },
                        new
                        {
                            Id = -9,
                            CreatedAt = new DateTime(2024, 11, 12, 4, 32, 8, 857, DateTimeKind.Local).AddTicks(8178),
                            Description = "Ea temporibus non eaque suscipit dolorum dolor.",
                            Name = "Licensed Plastic Shirt",
                            Price = 710.31m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 33, 55, 481, DateTimeKind.Local).AddTicks(3887)
                        },
                        new
                        {
                            Id = -10,
                            CreatedAt = new DateTime(2025, 4, 19, 13, 41, 2, 670, DateTimeKind.Local).AddTicks(7193),
                            Description = "Rerum saepe enim cupiditate blanditiis exercitationem est ab sed est.",
                            Name = "Sleek Soft Salad",
                            Price = 968.75m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 19, 55, 594, DateTimeKind.Local).AddTicks(5885)
                        },
                        new
                        {
                            Id = -11,
                            CreatedAt = new DateTime(2025, 2, 5, 11, 1, 14, 685, DateTimeKind.Local).AddTicks(1660),
                            Description = "Aperiam aut deserunt quod nam eos.",
                            Name = "Tasty Wooden Ball",
                            Price = 712.73m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 34, 6, 537, DateTimeKind.Local).AddTicks(1458)
                        },
                        new
                        {
                            Id = -12,
                            CreatedAt = new DateTime(2024, 6, 8, 10, 13, 51, 100, DateTimeKind.Local).AddTicks(9558),
                            Description = "Ut assumenda quidem nisi magnam accusamus ratione asperiores et.",
                            Name = "Small Fresh Shoes",
                            Price = 282.94m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 39, 38, 10, DateTimeKind.Local).AddTicks(8885)
                        },
                        new
                        {
                            Id = -13,
                            CreatedAt = new DateTime(2024, 6, 15, 20, 3, 55, 717, DateTimeKind.Local).AddTicks(892),
                            Description = "Soluta autem aut illum iusto illo quidem nisi.",
                            Name = "Licensed Metal Chicken",
                            Price = 827.49m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 55, 48, 266, DateTimeKind.Local).AddTicks(255)
                        },
                        new
                        {
                            Id = -14,
                            CreatedAt = new DateTime(2024, 10, 1, 20, 23, 16, 10, DateTimeKind.Local).AddTicks(5116),
                            Description = "Odio rerum voluptate eaque dolorem odio ipsam.",
                            Name = "Gorgeous Concrete Soap",
                            Price = 487.63m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 46, 48, 671, DateTimeKind.Local).AddTicks(6953)
                        },
                        new
                        {
                            Id = -15,
                            CreatedAt = new DateTime(2024, 10, 8, 5, 27, 46, 256, DateTimeKind.Local).AddTicks(2796),
                            Description = "Soluta rerum iste qui rerum qui laborum deleniti quae debitis.",
                            Name = "Gorgeous Rubber Computer",
                            Price = 422.36m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 46, 36, 737, DateTimeKind.Local).AddTicks(1576)
                        },
                        new
                        {
                            Id = -16,
                            CreatedAt = new DateTime(2024, 12, 27, 6, 47, 13, 611, DateTimeKind.Local).AddTicks(5296),
                            Description = "Inventore accusantium voluptas est at.",
                            Name = "Handcrafted Concrete Chips",
                            Price = 275.21m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 36, 45, 228, DateTimeKind.Local).AddTicks(8773)
                        },
                        new
                        {
                            Id = -17,
                            CreatedAt = new DateTime(2024, 10, 29, 6, 30, 30, 283, DateTimeKind.Local).AddTicks(5053),
                            Description = "Reiciendis consequatur beatae ipsam blanditiis est deserunt.",
                            Name = "Awesome Rubber Car",
                            Price = 179.42m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 52, 53, 404, DateTimeKind.Local).AddTicks(2258)
                        },
                        new
                        {
                            Id = -18,
                            CreatedAt = new DateTime(2025, 5, 20, 11, 34, 50, 610, DateTimeKind.Local).AddTicks(6011),
                            Description = "Dolorem facere qui qui tempore.",
                            Name = "Licensed Soft Computer",
                            Price = 467.51m,
                            UpdatedAt = new DateTime(2025, 6, 2, 11, 25, 27, 475, DateTimeKind.Local).AddTicks(3011)
                        },
                        new
                        {
                            Id = -19,
                            CreatedAt = new DateTime(2024, 11, 7, 3, 38, 16, 636, DateTimeKind.Local).AddTicks(9468),
                            Description = "Eum molestiae voluptates ipsam voluptatem nobis.",
                            Name = "Licensed Metal Keyboard",
                            Price = 358.79m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 58, 12, 203, DateTimeKind.Local).AddTicks(105)
                        },
                        new
                        {
                            Id = -20,
                            CreatedAt = new DateTime(2024, 6, 15, 15, 53, 50, 180, DateTimeKind.Local).AddTicks(7714),
                            Description = "Nihil amet vel autem impedit amet in laboriosam unde.",
                            Name = "Unbranded Soft Soap",
                            Price = 945.31m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 31, 47, 145, DateTimeKind.Local).AddTicks(5929)
                        },
                        new
                        {
                            Id = -21,
                            CreatedAt = new DateTime(2024, 10, 1, 12, 7, 53, 377, DateTimeKind.Local).AddTicks(1254),
                            Description = "Exercitationem dignissimos quo atque cum dolor magnam.",
                            Name = "Rustic Metal Soap",
                            Price = 617.04m,
                            UpdatedAt = new DateTime(2025, 6, 3, 9, 21, 29, 539, DateTimeKind.Local).AddTicks(8908)
                        },
                        new
                        {
                            Id = -22,
                            CreatedAt = new DateTime(2025, 2, 16, 8, 43, 51, 731, DateTimeKind.Local).AddTicks(2404),
                            Description = "Reiciendis eligendi delectus in cum dignissimos.",
                            Name = "Incredible Rubber Keyboard",
                            Price = 500.01m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 45, 17, 640, DateTimeKind.Local).AddTicks(6449)
                        },
                        new
                        {
                            Id = -23,
                            CreatedAt = new DateTime(2024, 6, 5, 1, 11, 19, 158, DateTimeKind.Local).AddTicks(5381),
                            Description = "Repudiandae in pariatur.",
                            Name = "Awesome Fresh Cheese",
                            Price = 876.12m,
                            UpdatedAt = new DateTime(2025, 6, 2, 22, 20, 36, 657, DateTimeKind.Local).AddTicks(5344)
                        },
                        new
                        {
                            Id = -24,
                            CreatedAt = new DateTime(2025, 1, 19, 19, 21, 35, 444, DateTimeKind.Local).AddTicks(6373),
                            Description = "Officia ut molestiae ea laudantium numquam voluptatibus possimus.",
                            Name = "Sleek Frozen Soap",
                            Price = 973.84m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 49, 19, 100, DateTimeKind.Local).AddTicks(6071)
                        },
                        new
                        {
                            Id = -25,
                            CreatedAt = new DateTime(2024, 9, 2, 17, 51, 58, 18, DateTimeKind.Local).AddTicks(2260),
                            Description = "Hic ut laboriosam minima in nam quo atque dicta vitae.",
                            Name = "Licensed Soft Towels",
                            Price = 874.17m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 47, 32, 18, DateTimeKind.Local).AddTicks(5884)
                        },
                        new
                        {
                            Id = -26,
                            CreatedAt = new DateTime(2025, 3, 4, 13, 4, 23, 516, DateTimeKind.Local).AddTicks(9274),
                            Description = "Cumque sed et laboriosam non sit omnis dolor officia.",
                            Name = "Handmade Soft Bacon",
                            Price = 917.20m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 1, 36, 564, DateTimeKind.Local).AddTicks(5678)
                        },
                        new
                        {
                            Id = -27,
                            CreatedAt = new DateTime(2024, 9, 18, 22, 30, 40, 116, DateTimeKind.Local).AddTicks(6479),
                            Description = "Itaque maiores magni voluptatem unde.",
                            Name = "Incredible Frozen Ball",
                            Price = 990.06m,
                            UpdatedAt = new DateTime(2025, 6, 3, 0, 49, 58, 451, DateTimeKind.Local).AddTicks(6206)
                        },
                        new
                        {
                            Id = -28,
                            CreatedAt = new DateTime(2024, 8, 9, 16, 23, 58, 806, DateTimeKind.Local).AddTicks(4779),
                            Description = "Doloremque est ullam dicta.",
                            Name = "Small Frozen Chair",
                            Price = 459.33m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 24, 6, 495, DateTimeKind.Local).AddTicks(8080)
                        },
                        new
                        {
                            Id = -29,
                            CreatedAt = new DateTime(2024, 9, 23, 6, 19, 24, 166, DateTimeKind.Local).AddTicks(2567),
                            Description = "Doloremque dolore deleniti soluta.",
                            Name = "Incredible Wooden Pants",
                            Price = 850.70m,
                            UpdatedAt = new DateTime(2025, 6, 3, 9, 20, 38, 416, DateTimeKind.Local).AddTicks(7048)
                        },
                        new
                        {
                            Id = -30,
                            CreatedAt = new DateTime(2024, 9, 25, 11, 2, 22, 450, DateTimeKind.Local).AddTicks(6881),
                            Description = "Et reiciendis odio minus.",
                            Name = "Handmade Plastic Chips",
                            Price = 992.58m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 53, 34, 334, DateTimeKind.Local).AddTicks(981)
                        },
                        new
                        {
                            Id = -31,
                            CreatedAt = new DateTime(2024, 10, 1, 20, 27, 30, 239, DateTimeKind.Local).AddTicks(1062),
                            Description = "Voluptatem illo quidem.",
                            Name = "Fantastic Soft Pants",
                            Price = 208.44m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 37, 54, 729, DateTimeKind.Local).AddTicks(1991)
                        },
                        new
                        {
                            Id = -32,
                            CreatedAt = new DateTime(2024, 12, 22, 23, 30, 4, 565, DateTimeKind.Local).AddTicks(6733),
                            Description = "Qui laborum ex quos beatae fugit incidunt nihil non perspiciatis.",
                            Name = "Incredible Granite Mouse",
                            Price = 399.51m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 33, 23, 941, DateTimeKind.Local).AddTicks(67)
                        },
                        new
                        {
                            Id = -33,
                            CreatedAt = new DateTime(2024, 10, 31, 7, 27, 37, 822, DateTimeKind.Local).AddTicks(200),
                            Description = "Repudiandae veritatis saepe repellendus facere.",
                            Name = "Handmade Frozen Table",
                            Price = 922.25m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 27, 16, 907, DateTimeKind.Local).AddTicks(7018)
                        },
                        new
                        {
                            Id = -34,
                            CreatedAt = new DateTime(2025, 3, 8, 5, 3, 1, 361, DateTimeKind.Local).AddTicks(4261),
                            Description = "Omnis dolorem rerum error mollitia ea rerum.",
                            Name = "Practical Concrete Salad",
                            Price = 611.51m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 20, 55, 612, DateTimeKind.Local).AddTicks(1118)
                        },
                        new
                        {
                            Id = -35,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 58, 36, 511, DateTimeKind.Local).AddTicks(4217),
                            Description = "Sit aliquam soluta.",
                            Name = "Rustic Frozen Hat",
                            Price = 25.93m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 44, 46, 857, DateTimeKind.Local).AddTicks(8271)
                        },
                        new
                        {
                            Id = -36,
                            CreatedAt = new DateTime(2024, 12, 3, 6, 59, 17, 513, DateTimeKind.Local).AddTicks(6282),
                            Description = "Autem quidem doloribus voluptatem quo sunt.",
                            Name = "Practical Cotton Fish",
                            Price = 328.24m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 48, 6, 26, DateTimeKind.Local).AddTicks(3045)
                        },
                        new
                        {
                            Id = -37,
                            CreatedAt = new DateTime(2024, 6, 17, 21, 4, 33, 685, DateTimeKind.Local).AddTicks(618),
                            Description = "Consequuntur pariatur quo dolorem in amet qui.",
                            Name = "Generic Cotton Mouse",
                            Price = 273.59m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 14, 3, 227, DateTimeKind.Local).AddTicks(7132)
                        },
                        new
                        {
                            Id = -38,
                            CreatedAt = new DateTime(2024, 6, 11, 14, 11, 27, 633, DateTimeKind.Local).AddTicks(6106),
                            Description = "Molestiae aut voluptatem.",
                            Name = "Rustic Metal Bacon",
                            Price = 220.01m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 53, 11, 117, DateTimeKind.Local).AddTicks(5208)
                        },
                        new
                        {
                            Id = -39,
                            CreatedAt = new DateTime(2025, 4, 17, 20, 7, 29, 882, DateTimeKind.Local).AddTicks(6494),
                            Description = "Voluptates neque aut corrupti.",
                            Name = "Tasty Metal Shirt",
                            Price = 245.62m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 50, 57, 606, DateTimeKind.Local).AddTicks(5548)
                        },
                        new
                        {
                            Id = -40,
                            CreatedAt = new DateTime(2025, 1, 12, 16, 49, 59, 249, DateTimeKind.Local).AddTicks(6369),
                            Description = "Itaque perferendis iusto odio.",
                            Name = "Incredible Granite Chair",
                            Price = 275.82m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 9, 30, 420, DateTimeKind.Local).AddTicks(3220)
                        },
                        new
                        {
                            Id = -41,
                            CreatedAt = new DateTime(2024, 10, 15, 8, 57, 54, 559, DateTimeKind.Local).AddTicks(5071),
                            Description = "Sint aut eos sed.",
                            Name = "Incredible Cotton Mouse",
                            Price = 211.66m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 54, 5, 261, DateTimeKind.Local).AddTicks(2420)
                        },
                        new
                        {
                            Id = -42,
                            CreatedAt = new DateTime(2024, 11, 27, 8, 13, 18, 203, DateTimeKind.Local).AddTicks(4498),
                            Description = "Ratione praesentium et excepturi odit recusandae reprehenderit.",
                            Name = "Handcrafted Frozen Chips",
                            Price = 209.97m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 52, 48, 390, DateTimeKind.Local).AddTicks(9944)
                        },
                        new
                        {
                            Id = -43,
                            CreatedAt = new DateTime(2024, 10, 10, 21, 4, 12, 909, DateTimeKind.Local).AddTicks(8445),
                            Description = "Ullam architecto et est ipsum sunt nemo neque.",
                            Name = "Incredible Rubber Car",
                            Price = 443.84m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 25, 13, 93, DateTimeKind.Local).AddTicks(2729)
                        },
                        new
                        {
                            Id = -44,
                            CreatedAt = new DateTime(2025, 1, 19, 16, 39, 19, 823, DateTimeKind.Local).AddTicks(1791),
                            Description = "Repudiandae tenetur est.",
                            Name = "Incredible Steel Ball",
                            Price = 855.06m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 4, 0, 754, DateTimeKind.Local).AddTicks(7248)
                        },
                        new
                        {
                            Id = -45,
                            CreatedAt = new DateTime(2024, 11, 18, 4, 25, 35, 853, DateTimeKind.Local).AddTicks(4839),
                            Description = "Deleniti quis facere quisquam veniam reiciendis ab fuga doloremque.",
                            Name = "Handmade Cotton Chair",
                            Price = 568.02m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 8, 57, 439, DateTimeKind.Local).AddTicks(1244)
                        },
                        new
                        {
                            Id = -46,
                            CreatedAt = new DateTime(2024, 12, 30, 23, 9, 4, 75, DateTimeKind.Local).AddTicks(8395),
                            Description = "Est architecto voluptatem.",
                            Name = "Rustic Wooden Sausages",
                            Price = 128.79m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 23, 42, 722, DateTimeKind.Local).AddTicks(9336)
                        },
                        new
                        {
                            Id = -47,
                            CreatedAt = new DateTime(2025, 5, 20, 10, 32, 22, 269, DateTimeKind.Local).AddTicks(6557),
                            Description = "Distinctio dolorem magni.",
                            Name = "Practical Plastic Shirt",
                            Price = 53.25m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 25, 35, 636, DateTimeKind.Local).AddTicks(4808)
                        },
                        new
                        {
                            Id = -48,
                            CreatedAt = new DateTime(2024, 10, 4, 3, 49, 4, 311, DateTimeKind.Local).AddTicks(2196),
                            Description = "Excepturi culpa perspiciatis voluptatibus repellendus expedita voluptatem aspernatur.",
                            Name = "Small Granite Salad",
                            Price = 65.12m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 47, 43, 546, DateTimeKind.Local).AddTicks(8914)
                        },
                        new
                        {
                            Id = -49,
                            CreatedAt = new DateTime(2024, 11, 23, 8, 26, 28, 759, DateTimeKind.Local).AddTicks(3401),
                            Description = "Enim porro velit ad rerum qui harum dolorum voluptatum.",
                            Name = "Handcrafted Metal Chair",
                            Price = 368.66m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 15, 11, 746, DateTimeKind.Local).AddTicks(8544)
                        },
                        new
                        {
                            Id = -50,
                            CreatedAt = new DateTime(2025, 5, 28, 16, 32, 53, 458, DateTimeKind.Local).AddTicks(8754),
                            Description = "Facere dolores aliquid.",
                            Name = "Licensed Rubber Chair",
                            Price = 343.56m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 40, 1, 196, DateTimeKind.Local).AddTicks(1923)
                        },
                        new
                        {
                            Id = -51,
                            CreatedAt = new DateTime(2025, 4, 6, 7, 36, 42, 611, DateTimeKind.Local).AddTicks(3562),
                            Description = "Et temporibus sint consequatur.",
                            Name = "Awesome Rubber Salad",
                            Price = 905.42m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 31, 23, 508, DateTimeKind.Local).AddTicks(1835)
                        },
                        new
                        {
                            Id = -52,
                            CreatedAt = new DateTime(2025, 5, 4, 10, 11, 11, 310, DateTimeKind.Local).AddTicks(5591),
                            Description = "Ut suscipit qui debitis quibusdam dolor.",
                            Name = "Handcrafted Concrete Pants",
                            Price = 248.58m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 16, 32, 760, DateTimeKind.Local).AddTicks(4739)
                        },
                        new
                        {
                            Id = -53,
                            CreatedAt = new DateTime(2024, 12, 14, 2, 45, 1, 286, DateTimeKind.Local).AddTicks(2204),
                            Description = "Rerum repellat eum iusto accusantium et harum.",
                            Name = "Awesome Metal Hat",
                            Price = 62.38m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 42, 40, 721, DateTimeKind.Local).AddTicks(2366)
                        },
                        new
                        {
                            Id = -54,
                            CreatedAt = new DateTime(2024, 10, 26, 7, 25, 15, 76, DateTimeKind.Local).AddTicks(5819),
                            Description = "Aut maiores voluptas consectetur delectus est assumenda minus ut sint.",
                            Name = "Unbranded Wooden Tuna",
                            Price = 45.56m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 58, 53, 871, DateTimeKind.Local).AddTicks(1229)
                        },
                        new
                        {
                            Id = -55,
                            CreatedAt = new DateTime(2025, 2, 6, 15, 57, 57, 38, DateTimeKind.Local).AddTicks(1632),
                            Description = "Neque laborum nobis.",
                            Name = "Gorgeous Rubber Cheese",
                            Price = 95.22m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 16, 0, 802, DateTimeKind.Local).AddTicks(1704)
                        },
                        new
                        {
                            Id = -56,
                            CreatedAt = new DateTime(2024, 9, 25, 4, 36, 8, 330, DateTimeKind.Local).AddTicks(6331),
                            Description = "Vitae est ea voluptas sed ut cupiditate officia magni.",
                            Name = "Gorgeous Fresh Chicken",
                            Price = 133.98m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 14, 32, 142, DateTimeKind.Local).AddTicks(4505)
                        },
                        new
                        {
                            Id = -57,
                            CreatedAt = new DateTime(2025, 1, 11, 22, 41, 46, 866, DateTimeKind.Local).AddTicks(8063),
                            Description = "Et possimus at ut quam consequatur quisquam.",
                            Name = "Incredible Cotton Chair",
                            Price = 62.04m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 29, 21, 666, DateTimeKind.Local).AddTicks(2278)
                        },
                        new
                        {
                            Id = -58,
                            CreatedAt = new DateTime(2025, 2, 6, 18, 52, 44, 157, DateTimeKind.Local).AddTicks(1827),
                            Description = "Mollitia voluptas sint ut eligendi in corrupti et quis itaque.",
                            Name = "Handmade Cotton Shirt",
                            Price = 100.70m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 25, 44, 567, DateTimeKind.Local).AddTicks(8830)
                        },
                        new
                        {
                            Id = -59,
                            CreatedAt = new DateTime(2024, 9, 4, 0, 40, 23, 411, DateTimeKind.Local).AddTicks(4733),
                            Description = "Id qui illo dolorem blanditiis facilis repellendus aut error molestiae.",
                            Name = "Handcrafted Plastic Shoes",
                            Price = 409.99m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 29, 27, 61, DateTimeKind.Local).AddTicks(8900)
                        },
                        new
                        {
                            Id = -60,
                            CreatedAt = new DateTime(2024, 7, 24, 11, 3, 6, 794, DateTimeKind.Local).AddTicks(3841),
                            Description = "Doloribus omnis et consequuntur occaecati minus.",
                            Name = "Refined Fresh Computer",
                            Price = 287.69m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 18, 46, 502, DateTimeKind.Local).AddTicks(1009)
                        },
                        new
                        {
                            Id = -61,
                            CreatedAt = new DateTime(2024, 7, 21, 20, 46, 48, 56, DateTimeKind.Local).AddTicks(8632),
                            Description = "Vero et fugiat sit ad molestiae dolore.",
                            Name = "Handmade Soft Tuna",
                            Price = 648.74m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 31, 30, 141, DateTimeKind.Local).AddTicks(7242)
                        },
                        new
                        {
                            Id = -62,
                            CreatedAt = new DateTime(2025, 4, 9, 18, 58, 47, 360, DateTimeKind.Local).AddTicks(6099),
                            Description = "Adipisci quia eveniet maxime deleniti omnis praesentium est.",
                            Name = "Refined Plastic Keyboard",
                            Price = 892.03m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 4, 13, 140, DateTimeKind.Local).AddTicks(1773)
                        },
                        new
                        {
                            Id = -63,
                            CreatedAt = new DateTime(2024, 12, 21, 17, 26, 13, 929, DateTimeKind.Local).AddTicks(4190),
                            Description = "Sequi voluptatem voluptatem impedit temporibus.",
                            Name = "Licensed Frozen Chicken",
                            Price = 835.08m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 49, 3, 34, DateTimeKind.Local).AddTicks(6930)
                        },
                        new
                        {
                            Id = -64,
                            CreatedAt = new DateTime(2024, 7, 12, 15, 14, 21, 309, DateTimeKind.Local).AddTicks(8143),
                            Description = "Doloremque officiis quod doloremque enim quas vel.",
                            Name = "Handmade Plastic Computer",
                            Price = 353.71m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 49, 16, 748, DateTimeKind.Local).AddTicks(8713)
                        },
                        new
                        {
                            Id = -65,
                            CreatedAt = new DateTime(2024, 12, 8, 23, 33, 35, 179, DateTimeKind.Local).AddTicks(2625),
                            Description = "Velit ut a et rem aut quam sunt blanditiis.",
                            Name = "Handcrafted Plastic Cheese",
                            Price = 369.89m,
                            UpdatedAt = new DateTime(2025, 6, 3, 9, 39, 25, 147, DateTimeKind.Local).AddTicks(2523)
                        },
                        new
                        {
                            Id = -66,
                            CreatedAt = new DateTime(2025, 1, 24, 3, 39, 32, 982, DateTimeKind.Local).AddTicks(4485),
                            Description = "Ex eaque est accusantium omnis.",
                            Name = "Intelligent Granite Car",
                            Price = 626.00m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 14, 26, 124, DateTimeKind.Local).AddTicks(7366)
                        },
                        new
                        {
                            Id = -67,
                            CreatedAt = new DateTime(2024, 10, 1, 20, 24, 27, 684, DateTimeKind.Local).AddTicks(5292),
                            Description = "Enim quidem enim asperiores nihil ea consequatur eum et.",
                            Name = "Tasty Frozen Shirt",
                            Price = 838.78m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 27, 27, 379, DateTimeKind.Local).AddTicks(8741)
                        },
                        new
                        {
                            Id = -68,
                            CreatedAt = new DateTime(2025, 1, 22, 5, 39, 1, 749, DateTimeKind.Local).AddTicks(7048),
                            Description = "Inventore quia ut exercitationem saepe qui.",
                            Name = "Incredible Cotton Sausages",
                            Price = 989.31m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 33, 27, 614, DateTimeKind.Local).AddTicks(5972)
                        },
                        new
                        {
                            Id = -69,
                            CreatedAt = new DateTime(2024, 8, 20, 22, 3, 26, 755, DateTimeKind.Local).AddTicks(9032),
                            Description = "Debitis quos vel quae.",
                            Name = "Licensed Plastic Pizza",
                            Price = 136.36m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 19, 33, 701, DateTimeKind.Local).AddTicks(6363)
                        },
                        new
                        {
                            Id = -70,
                            CreatedAt = new DateTime(2024, 6, 26, 0, 30, 57, 804, DateTimeKind.Local).AddTicks(3414),
                            Description = "Qui dolor et.",
                            Name = "Ergonomic Metal Keyboard",
                            Price = 246.34m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 31, 55, 211, DateTimeKind.Local).AddTicks(1261)
                        },
                        new
                        {
                            Id = -71,
                            CreatedAt = new DateTime(2025, 4, 6, 19, 2, 20, 127, DateTimeKind.Local).AddTicks(2862),
                            Description = "Dolore consequatur voluptas qui.",
                            Name = "Small Soft Bacon",
                            Price = 731.00m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 18, 32, 806, DateTimeKind.Local).AddTicks(8544)
                        },
                        new
                        {
                            Id = -72,
                            CreatedAt = new DateTime(2024, 8, 2, 17, 24, 26, 736, DateTimeKind.Local).AddTicks(2482),
                            Description = "Ea omnis voluptatum nam mollitia aut est porro.",
                            Name = "Handcrafted Granite Keyboard",
                            Price = 504.90m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 8, 23, 269, DateTimeKind.Local).AddTicks(2007)
                        },
                        new
                        {
                            Id = -73,
                            CreatedAt = new DateTime(2025, 3, 6, 1, 17, 15, 887, DateTimeKind.Local).AddTicks(6835),
                            Description = "Nam vel beatae velit laboriosam inventore consectetur aut id deleniti.",
                            Name = "Intelligent Soft Towels",
                            Price = 87.55m,
                            UpdatedAt = new DateTime(2025, 6, 3, 11, 12, 17, 150, DateTimeKind.Local).AddTicks(4724)
                        },
                        new
                        {
                            Id = -74,
                            CreatedAt = new DateTime(2024, 7, 31, 23, 17, 18, 840, DateTimeKind.Local).AddTicks(4569),
                            Description = "Voluptatem nostrum aperiam pariatur in perferendis est dolorem.",
                            Name = "Sleek Metal Chicken",
                            Price = 602.23m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 51, 38, 287, DateTimeKind.Local).AddTicks(5272)
                        },
                        new
                        {
                            Id = -75,
                            CreatedAt = new DateTime(2024, 6, 27, 3, 36, 49, 317, DateTimeKind.Local).AddTicks(361),
                            Description = "Neque dolor voluptatem voluptatem vel nemo illo.",
                            Name = "Rustic Rubber Cheese",
                            Price = 157.06m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 46, 13, 83, DateTimeKind.Local).AddTicks(7407)
                        },
                        new
                        {
                            Id = -76,
                            CreatedAt = new DateTime(2025, 2, 20, 7, 11, 12, 391, DateTimeKind.Local).AddTicks(2376),
                            Description = "Est molestias nihil nesciunt enim aut odio dolore necessitatibus.",
                            Name = "Handcrafted Cotton Pizza",
                            Price = 908.28m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 25, 10, 168, DateTimeKind.Local).AddTicks(2344)
                        },
                        new
                        {
                            Id = -77,
                            CreatedAt = new DateTime(2024, 7, 29, 10, 38, 42, 183, DateTimeKind.Local).AddTicks(4457),
                            Description = "Odit est quibusdam consequuntur dolores voluptatum et occaecati illo.",
                            Name = "Awesome Granite Bike",
                            Price = 924.15m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 9, 0, 411, DateTimeKind.Local).AddTicks(5906)
                        },
                        new
                        {
                            Id = -78,
                            CreatedAt = new DateTime(2024, 10, 12, 1, 23, 42, 626, DateTimeKind.Local).AddTicks(8717),
                            Description = "Voluptatem sunt soluta dignissimos nesciunt distinctio nihil odit.",
                            Name = "Licensed Fresh Pizza",
                            Price = 510.81m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 15, 45, 689, DateTimeKind.Local).AddTicks(8112)
                        },
                        new
                        {
                            Id = -79,
                            CreatedAt = new DateTime(2024, 6, 22, 6, 26, 43, 518, DateTimeKind.Local).AddTicks(8642),
                            Description = "Sit est sunt nihil corporis.",
                            Name = "Ergonomic Metal Sausages",
                            Price = 853.34m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 42, 17, 512, DateTimeKind.Local).AddTicks(3144)
                        },
                        new
                        {
                            Id = -80,
                            CreatedAt = new DateTime(2024, 10, 9, 14, 14, 12, 257, DateTimeKind.Local).AddTicks(1099),
                            Description = "Aperiam quia fuga nam consequatur et voluptatem maiores.",
                            Name = "Sleek Soft Pants",
                            Price = 968.05m,
                            UpdatedAt = new DateTime(2025, 6, 3, 0, 14, 18, 950, DateTimeKind.Local).AddTicks(3178)
                        },
                        new
                        {
                            Id = -81,
                            CreatedAt = new DateTime(2025, 2, 16, 23, 20, 49, 746, DateTimeKind.Local).AddTicks(474),
                            Description = "Eveniet beatae sit.",
                            Name = "Incredible Metal Car",
                            Price = 199.77m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 2, 59, 175, DateTimeKind.Local).AddTicks(4229)
                        },
                        new
                        {
                            Id = -82,
                            CreatedAt = new DateTime(2025, 3, 17, 2, 51, 41, 292, DateTimeKind.Local).AddTicks(3501),
                            Description = "Asperiores aut non mollitia quae sunt beatae voluptatem quia quia.",
                            Name = "Small Wooden Shoes",
                            Price = 243.02m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 47, 20, 733, DateTimeKind.Local).AddTicks(2344)
                        },
                        new
                        {
                            Id = -83,
                            CreatedAt = new DateTime(2025, 1, 11, 2, 6, 29, 7, DateTimeKind.Local).AddTicks(6840),
                            Description = "Suscipit est et dignissimos.",
                            Name = "Tasty Granite Computer",
                            Price = 153.06m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 59, 5, 526, DateTimeKind.Local).AddTicks(327)
                        },
                        new
                        {
                            Id = -84,
                            CreatedAt = new DateTime(2024, 7, 21, 1, 43, 19, 846, DateTimeKind.Local).AddTicks(1010),
                            Description = "Odit officiis qui nihil ut tempore voluptatem.",
                            Name = "Unbranded Concrete Keyboard",
                            Price = 781.50m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 5, 9, 463, DateTimeKind.Local).AddTicks(9948)
                        },
                        new
                        {
                            Id = -85,
                            CreatedAt = new DateTime(2025, 4, 16, 19, 18, 38, 689, DateTimeKind.Local).AddTicks(5797),
                            Description = "Sit unde deserunt.",
                            Name = "Tasty Plastic Sausages",
                            Price = 75.91m,
                            UpdatedAt = new DateTime(2025, 6, 2, 11, 49, 36, 371, DateTimeKind.Local).AddTicks(4561)
                        },
                        new
                        {
                            Id = -86,
                            CreatedAt = new DateTime(2025, 5, 29, 4, 47, 33, 826, DateTimeKind.Local).AddTicks(8633),
                            Description = "Inventore perferendis consectetur.",
                            Name = "Unbranded Rubber Fish",
                            Price = 210.65m,
                            UpdatedAt = new DateTime(2025, 6, 3, 4, 37, 21, 949, DateTimeKind.Local).AddTicks(9538)
                        },
                        new
                        {
                            Id = -87,
                            CreatedAt = new DateTime(2025, 4, 9, 14, 14, 3, 350, DateTimeKind.Local).AddTicks(4282),
                            Description = "Quis veniam dolor molestias error dolores quo quam doloremque.",
                            Name = "Sleek Plastic Chair",
                            Price = 636.02m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 46, 28, 386, DateTimeKind.Local).AddTicks(1223)
                        },
                        new
                        {
                            Id = -88,
                            CreatedAt = new DateTime(2025, 2, 6, 5, 2, 46, 567, DateTimeKind.Local).AddTicks(5795),
                            Description = "Molestiae quo et.",
                            Name = "Practical Steel Soap",
                            Price = 462.42m,
                            UpdatedAt = new DateTime(2025, 6, 3, 4, 15, 59, 413, DateTimeKind.Local).AddTicks(3481)
                        },
                        new
                        {
                            Id = -89,
                            CreatedAt = new DateTime(2025, 3, 4, 20, 27, 50, 71, DateTimeKind.Local).AddTicks(3742),
                            Description = "Officia laborum ut qui sunt.",
                            Name = "Intelligent Wooden Table",
                            Price = 941.24m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 17, 56, 27, DateTimeKind.Local).AddTicks(6012)
                        },
                        new
                        {
                            Id = -90,
                            CreatedAt = new DateTime(2025, 4, 24, 12, 58, 53, 999, DateTimeKind.Local).AddTicks(5247),
                            Description = "Consequatur et alias voluptatem in nulla molestiae quaerat vero vel.",
                            Name = "Handmade Concrete Shirt",
                            Price = 358.37m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 11, 47, 956, DateTimeKind.Local).AddTicks(5315)
                        },
                        new
                        {
                            Id = -91,
                            CreatedAt = new DateTime(2024, 6, 21, 0, 44, 3, 256, DateTimeKind.Local).AddTicks(7899),
                            Description = "Explicabo sed ipsa iure explicabo vitae quidem alias optio.",
                            Name = "Tasty Concrete Shoes",
                            Price = 206.32m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 3, 31, 885, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = -92,
                            CreatedAt = new DateTime(2025, 1, 5, 21, 52, 13, 486, DateTimeKind.Local).AddTicks(6817),
                            Description = "Omnis praesentium sit cupiditate.",
                            Name = "Refined Fresh Chair",
                            Price = 807.24m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 12, 28, 47, DateTimeKind.Local).AddTicks(6286)
                        },
                        new
                        {
                            Id = -93,
                            CreatedAt = new DateTime(2025, 5, 19, 7, 59, 19, 145, DateTimeKind.Local).AddTicks(3044),
                            Description = "Maxime corporis aut reprehenderit aspernatur voluptas et.",
                            Name = "Unbranded Wooden Pizza",
                            Price = 287.31m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 8, 41, 849, DateTimeKind.Local).AddTicks(4586)
                        },
                        new
                        {
                            Id = -94,
                            CreatedAt = new DateTime(2025, 5, 22, 2, 53, 11, 766, DateTimeKind.Local).AddTicks(6662),
                            Description = "Iste blanditiis omnis labore rerum omnis atque occaecati.",
                            Name = "Practical Wooden Sausages",
                            Price = 472.86m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 26, 17, 98, DateTimeKind.Local).AddTicks(3699)
                        },
                        new
                        {
                            Id = -95,
                            CreatedAt = new DateTime(2024, 9, 30, 2, 41, 3, 515, DateTimeKind.Local).AddTicks(5527),
                            Description = "Voluptatibus similique voluptatem quod deleniti et.",
                            Name = "Fantastic Frozen Gloves",
                            Price = 672.01m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 29, 0, 687, DateTimeKind.Local).AddTicks(9556)
                        },
                        new
                        {
                            Id = -96,
                            CreatedAt = new DateTime(2025, 5, 19, 18, 19, 20, 663, DateTimeKind.Local).AddTicks(8540),
                            Description = "Rem atque et consequuntur aliquid tempore.",
                            Name = "Ergonomic Concrete Chicken",
                            Price = 309.25m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 47, 31, 75, DateTimeKind.Local).AddTicks(3978)
                        },
                        new
                        {
                            Id = -97,
                            CreatedAt = new DateTime(2024, 12, 17, 21, 58, 45, 764, DateTimeKind.Local).AddTicks(9150),
                            Description = "Quasi a quibusdam.",
                            Name = "Generic Granite Sausages",
                            Price = 511.29m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 28, 29, 577, DateTimeKind.Local).AddTicks(4386)
                        },
                        new
                        {
                            Id = -98,
                            CreatedAt = new DateTime(2024, 9, 24, 1, 22, 1, 926, DateTimeKind.Local).AddTicks(7837),
                            Description = "Tenetur id quod nam similique autem ut in recusandae.",
                            Name = "Generic Steel Bacon",
                            Price = 411.86m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 57, 30, 155, DateTimeKind.Local).AddTicks(3503)
                        },
                        new
                        {
                            Id = -99,
                            CreatedAt = new DateTime(2024, 6, 9, 9, 7, 17, 242, DateTimeKind.Local).AddTicks(6004),
                            Description = "Eius quia id aut voluptas perspiciatis minus delectus.",
                            Name = "Handcrafted Frozen Pizza",
                            Price = 11.88m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 51, 34, 968, DateTimeKind.Local).AddTicks(7395)
                        },
                        new
                        {
                            Id = -100,
                            CreatedAt = new DateTime(2024, 7, 18, 14, 29, 37, 431, DateTimeKind.Local).AddTicks(1599),
                            Description = "Ipsum adipisci cumque eum possimus.",
                            Name = "Intelligent Metal Pizza",
                            Price = 346.21m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 19, 55, 607, DateTimeKind.Local).AddTicks(2161)
                        });
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TemplateFramework.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
