// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateFramework.Infastructure.Data;

#nullable disable

namespace TemplateFramework.Infastructure.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20250603042248_db6")]
    partial class db6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TemplateFramework.Domain.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 29, 15, 29, 30, 802, DateTimeKind.Local).AddTicks(4461),
                            Description = "Distinctio saepe quae inventore repudiandae magni et.",
                            Name = "Intelligent Steel Salad",
                            Price = 220.72m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 31, 26, 625, DateTimeKind.Local).AddTicks(6240)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 22, 12, 0, 12, 358, DateTimeKind.Local).AddTicks(3466),
                            Description = "Debitis nam totam.",
                            Name = "Handcrafted Rubber Chair",
                            Price = 295.58m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 12, 50, 176, DateTimeKind.Local).AddTicks(1627)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 20, 12, 41, 14, 950, DateTimeKind.Local).AddTicks(5752),
                            Description = "Et sit corporis nobis sint rem saepe est autem nulla.",
                            Name = "Unbranded Concrete Fish",
                            Price = 713.36m,
                            UpdatedAt = new DateTime(2025, 6, 3, 11, 18, 34, 41, DateTimeKind.Local).AddTicks(2163)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 7, 23, 19, 20, 58, 81, DateTimeKind.Local).AddTicks(8629),
                            Description = "Similique et et provident aut.",
                            Name = "Handmade Concrete Hat",
                            Price = 97.77m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 22, 34, 265, DateTimeKind.Local).AddTicks(5248)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 3, 16, 56, 49, 490, DateTimeKind.Local).AddTicks(6153),
                            Description = "Maxime quia et consequatur neque ex consequatur.",
                            Name = "Handcrafted Soft Chips",
                            Price = 523.95m,
                            UpdatedAt = new DateTime(2025, 6, 3, 7, 44, 26, 534, DateTimeKind.Local).AddTicks(7167)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 9, 7, 19, 45, 10, 490, DateTimeKind.Local).AddTicks(8296),
                            Description = "Minima consequuntur voluptatum facilis nemo.",
                            Name = "Rustic Concrete Salad",
                            Price = 46.98m,
                            UpdatedAt = new DateTime(2025, 6, 2, 22, 52, 40, 92, DateTimeKind.Local).AddTicks(2731)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 6, 18, 20, 47, 24, 681, DateTimeKind.Local).AddTicks(9268),
                            Description = "Eum rerum et ex voluptates voluptatem qui voluptatibus.",
                            Name = "Awesome Wooden Towels",
                            Price = 98.80m,
                            UpdatedAt = new DateTime(2025, 6, 2, 11, 39, 19, 278, DateTimeKind.Local).AddTicks(682)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 1, 22, 17, 19, 386, DateTimeKind.Local).AddTicks(3243),
                            Description = "Harum omnis vel blanditiis exercitationem distinctio.",
                            Name = "Licensed Wooden Shoes",
                            Price = 15.45m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 48, 10, 747, DateTimeKind.Local).AddTicks(7130)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 21, 14, 5, 27, 277, DateTimeKind.Local).AddTicks(1396),
                            Description = "Voluptatem velit fuga.",
                            Name = "Awesome Cotton Towels",
                            Price = 885.70m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 52, 35, 591, DateTimeKind.Local).AddTicks(3570)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 7, 6, 4, 44, 13, 666, DateTimeKind.Local).AddTicks(5557),
                            Description = "Accusamus voluptas ea nam quasi quod sunt libero aperiam doloremque.",
                            Name = "Intelligent Soft Shoes",
                            Price = 322.50m,
                            UpdatedAt = new DateTime(2025, 6, 3, 0, 30, 46, 757, DateTimeKind.Local).AddTicks(3942)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 5, 25, 10, 39, 9, 447, DateTimeKind.Local).AddTicks(4433),
                            Description = "Illum aliquam nobis commodi omnis.",
                            Name = "Fantastic Steel Towels",
                            Price = 445.05m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 43, 40, 657, DateTimeKind.Local).AddTicks(1554)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 2, 11, 15, 20, 3, 909, DateTimeKind.Local).AddTicks(5237),
                            Description = "Cum tenetur beatae voluptate enim consequatur sed eveniet et ut.",
                            Name = "Incredible Concrete Chips",
                            Price = 306.98m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 32, 20, 474, DateTimeKind.Local).AddTicks(446)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 5, 18, 2, 12, 0, 943, DateTimeKind.Local).AddTicks(1103),
                            Description = "Eos dolorem autem ab iusto non voluptas excepturi blanditiis et.",
                            Name = "Unbranded Cotton Soap",
                            Price = 279.84m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 45, 56, 399, DateTimeKind.Local).AddTicks(4562)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 12, 6, 10, 8, 49, 684, DateTimeKind.Local).AddTicks(3726),
                            Description = "Quia aliquam ut accusantium voluptatum voluptatem.",
                            Name = "Practical Plastic Sausages",
                            Price = 386.17m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 54, 2, 661, DateTimeKind.Local).AddTicks(2299)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 10, 17, 5, 25, 41, 92, DateTimeKind.Local).AddTicks(9411),
                            Description = "Dolores sit minus ipsam pariatur esse hic cupiditate enim.",
                            Name = "Fantastic Concrete Keyboard",
                            Price = 984.71m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 15, 57, 320, DateTimeKind.Local).AddTicks(13)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 12, 26, 8, 45, 33, 464, DateTimeKind.Local).AddTicks(9025),
                            Description = "Sint quod harum quaerat temporibus aliquam.",
                            Name = "Handmade Concrete Fish",
                            Price = 675.11m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 58, 23, 26, DateTimeKind.Local).AddTicks(570)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 6, 7, 18, 13, 35, 407, DateTimeKind.Local).AddTicks(5244),
                            Description = "Sit consequatur qui ipsam.",
                            Name = "Tasty Metal Car",
                            Price = 150.96m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 13, 28, 335, DateTimeKind.Local).AddTicks(5911)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 3, 13, 8, 56, 2, 198, DateTimeKind.Local).AddTicks(7934),
                            Description = "Debitis blanditiis recusandae cum consequatur voluptatum alias.",
                            Name = "Unbranded Fresh Pizza",
                            Price = 686.49m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 39, 16, 362, DateTimeKind.Local).AddTicks(313)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 11, 25, 3, 16, 26, 993, DateTimeKind.Local).AddTicks(7727),
                            Description = "Ducimus ad eius delectus aut ipsam nihil ducimus.",
                            Name = "Unbranded Fresh Keyboard",
                            Price = 798.79m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 29, 53, 132, DateTimeKind.Local).AddTicks(517)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 5, 12, 12, 38, 32, 285, DateTimeKind.Local).AddTicks(3707),
                            Description = "Possimus corporis dolorem veniam tenetur ut.",
                            Name = "Intelligent Steel Hat",
                            Price = 724.36m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 11, 43, 755, DateTimeKind.Local).AddTicks(4860)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 7, 3, 6, 6, 14, 599, DateTimeKind.Local).AddTicks(4140),
                            Description = "Dolorem amet est magni quas aut aut iste.",
                            Name = "Generic Steel Gloves",
                            Price = 143.51m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 25, 36, 109, DateTimeKind.Local).AddTicks(1522)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 12, 16, 11, 23, 5, 481, DateTimeKind.Local).AddTicks(7682),
                            Description = "Ab voluptas ut quia.",
                            Name = "Awesome Plastic Salad",
                            Price = 234.66m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 49, 33, 511, DateTimeKind.Local).AddTicks(7346)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 9, 30, 14, 29, 48, 274, DateTimeKind.Local).AddTicks(8411),
                            Description = "Quia quas incidunt ipsum quia enim quisquam autem consequatur.",
                            Name = "Handcrafted Fresh Shoes",
                            Price = 801.13m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 8, 47, 522, DateTimeKind.Local).AddTicks(9054)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 3, 9, 5, 14, 43, 340, DateTimeKind.Local).AddTicks(5242),
                            Description = "Dolorum hic ab aperiam maxime a adipisci quis.",
                            Name = "Tasty Rubber Chips",
                            Price = 536.26m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 17, 42, 374, DateTimeKind.Local).AddTicks(1438)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 11, 1, 5, 21, 12, 712, DateTimeKind.Local).AddTicks(5913),
                            Description = "Aut vel consequatur repellat assumenda.",
                            Name = "Fantastic Wooden Hat",
                            Price = 433.43m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 39, 27, 134, DateTimeKind.Local).AddTicks(185)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 9, 22, 3, 48, 31, 863, DateTimeKind.Local).AddTicks(9592),
                            Description = "Quis sed unde dolorem dolor quod veritatis dolore ea.",
                            Name = "Small Metal Cheese",
                            Price = 189.86m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 38, 59, 848, DateTimeKind.Local).AddTicks(785)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 9, 4, 1, 24, 10, 486, DateTimeKind.Local).AddTicks(8787),
                            Description = "Recusandae sequi et aut libero voluptas assumenda iusto eos soluta.",
                            Name = "Refined Plastic Gloves",
                            Price = 873.60m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 6, 44, 431, DateTimeKind.Local).AddTicks(2971)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 4, 3, 8, 28, 47, 687, DateTimeKind.Local).AddTicks(5675),
                            Description = "Hic commodi et qui blanditiis ipsum aut aspernatur rem.",
                            Name = "Licensed Granite Fish",
                            Price = 461.88m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 37, 16, 467, DateTimeKind.Local).AddTicks(476)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 3, 13, 23, 28, 59, 414, DateTimeKind.Local).AddTicks(3695),
                            Description = "Voluptate excepturi libero possimus.",
                            Name = "Generic Fresh Keyboard",
                            Price = 20.46m,
                            UpdatedAt = new DateTime(2025, 6, 3, 9, 12, 43, 894, DateTimeKind.Local).AddTicks(6447)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 12, 3, 15, 23, 23, 186, DateTimeKind.Local).AddTicks(453),
                            Description = "Quibusdam quo commodi numquam magnam perferendis aut voluptas nihil dolores.",
                            Name = "Practical Wooden Cheese",
                            Price = 124.36m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 7, 42, 516, DateTimeKind.Local).AddTicks(6871)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 10, 22, 7, 30, 32, 94, DateTimeKind.Local).AddTicks(8112),
                            Description = "Non dolor non facilis voluptatum ut ut eum.",
                            Name = "Licensed Soft Gloves",
                            Price = 929.14m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 21, 5, 364, DateTimeKind.Local).AddTicks(2793)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 3, 6, 16, 56, 48, 614, DateTimeKind.Local).AddTicks(7094),
                            Description = "In sit incidunt alias nostrum.",
                            Name = "Fantastic Wooden Cheese",
                            Price = 228.33m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 38, 1, 935, DateTimeKind.Local).AddTicks(7133)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 1, 10, 13, 13, 17, 768, DateTimeKind.Local).AddTicks(3624),
                            Description = "Qui eum aliquid repellendus vitae.",
                            Name = "Generic Granite Chair",
                            Price = 368.45m,
                            UpdatedAt = new DateTime(2025, 6, 2, 23, 56, 20, 859, DateTimeKind.Local).AddTicks(5988)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 11, 12, 2, 55, 29, 687, DateTimeKind.Local).AddTicks(6947),
                            Description = "Repellat dolorem explicabo expedita nulla enim sit ex.",
                            Name = "Fantastic Cotton Table",
                            Price = 992.83m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 12, 32, 429, DateTimeKind.Local).AddTicks(8774)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 1, 21, 15, 53, 41, 927, DateTimeKind.Local).AddTicks(2156),
                            Description = "Cum vero vero aspernatur sit.",
                            Name = "Awesome Metal Shirt",
                            Price = 109.41m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 44, 40, 33, DateTimeKind.Local).AddTicks(6404)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 3, 27, 23, 10, 59, 264, DateTimeKind.Local).AddTicks(6890),
                            Description = "Ipsum quidem quo molestiae qui nemo.",
                            Name = "Handmade Steel Table",
                            Price = 875.17m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 15, 43, 514, DateTimeKind.Local).AddTicks(7870)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 7, 11, 10, 31, 5, 133, DateTimeKind.Local).AddTicks(3017),
                            Description = "A ipsum sit sunt pariatur non natus exercitationem possimus.",
                            Name = "Gorgeous Steel Sausages",
                            Price = 743.88m,
                            UpdatedAt = new DateTime(2025, 6, 3, 7, 33, 34, 338, DateTimeKind.Local).AddTicks(6172)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 8, 31, 11, 10, 54, 859, DateTimeKind.Local).AddTicks(4913),
                            Description = "Dicta incidunt quidem sed fuga quidem deserunt sed accusamus.",
                            Name = "Awesome Concrete Fish",
                            Price = 411.05m,
                            UpdatedAt = new DateTime(2025, 6, 2, 11, 52, 58, 806, DateTimeKind.Local).AddTicks(755)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 12, 25, 9, 7, 26, 906, DateTimeKind.Local).AddTicks(3832),
                            Description = "Esse modi quis eos harum.",
                            Name = "Tasty Cotton Mouse",
                            Price = 674.36m,
                            UpdatedAt = new DateTime(2025, 6, 3, 9, 48, 16, 42, DateTimeKind.Local).AddTicks(5141)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 1, 26, 9, 11, 55, 270, DateTimeKind.Local).AddTicks(1538),
                            Description = "Quasi porro rerum laudantium ut aliquam.",
                            Name = "Incredible Wooden Hat",
                            Price = 551.24m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 43, 55, 547, DateTimeKind.Local).AddTicks(1677)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 10, 11, 14, 45, 49, 634, DateTimeKind.Local).AddTicks(6977),
                            Description = "Sed qui at sed veniam delectus molestiae temporibus id.",
                            Name = "Sleek Cotton Chips",
                            Price = 62.31m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 37, 10, 496, DateTimeKind.Local).AddTicks(9595)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 7, 5, 10, 24, 27, 890, DateTimeKind.Local).AddTicks(3100),
                            Description = "Similique inventore rerum nemo qui praesentium ut.",
                            Name = "Tasty Wooden Car",
                            Price = 895.64m,
                            UpdatedAt = new DateTime(2025, 6, 3, 6, 49, 3, 769, DateTimeKind.Local).AddTicks(5255)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 5, 15, 5, 56, 0, 408, DateTimeKind.Local).AddTicks(9349),
                            Description = "Aut nesciunt ducimus odio id saepe.",
                            Name = "Sleek Plastic Hat",
                            Price = 348.49m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 38, 22, 646, DateTimeKind.Local).AddTicks(9681)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 8, 22, 22, 12, 47, 901, DateTimeKind.Local).AddTicks(2057),
                            Description = "Et aliquam cum corrupti amet et ipsa sed nihil unde.",
                            Name = "Refined Soft Fish",
                            Price = 430.21m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 36, 20, 116, DateTimeKind.Local).AddTicks(1757)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 1, 29, 5, 52, 3, 217, DateTimeKind.Local).AddTicks(6523),
                            Description = "Atque rem qui est dolores ea deleniti.",
                            Name = "Licensed Rubber Soap",
                            Price = 553.32m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 40, 25, 192, DateTimeKind.Local).AddTicks(3666)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 11, 11, 1, 48, 50, 523, DateTimeKind.Local).AddTicks(1073),
                            Description = "Eum molestiae ullam.",
                            Name = "Sleek Wooden Pants",
                            Price = 735.16m,
                            UpdatedAt = new DateTime(2025, 6, 3, 7, 19, 17, 952, DateTimeKind.Local).AddTicks(786)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 3, 18, 15, 37, 13, 326, DateTimeKind.Local).AddTicks(50),
                            Description = "Asperiores et deserunt.",
                            Name = "Gorgeous Cotton Towels",
                            Price = 447.46m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 9, 55, 570, DateTimeKind.Local).AddTicks(7502)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 2, 9, 15, 55, 51, 512, DateTimeKind.Local).AddTicks(8333),
                            Description = "Doloremque ratione aliquid aliquam dolor officia sint vel qui totam.",
                            Name = "Refined Steel Chair",
                            Price = 406.13m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 9, 50, 581, DateTimeKind.Local).AddTicks(4700)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 10, 25, 6, 44, 43, 948, DateTimeKind.Local).AddTicks(2582),
                            Description = "Temporibus unde eum.",
                            Name = "Intelligent Steel Gloves",
                            Price = 552.93m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 34, 0, 347, DateTimeKind.Local).AddTicks(1447)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 11, 2, 7, 43, 51, 303, DateTimeKind.Local).AddTicks(1001),
                            Description = "Rerum enim consectetur.",
                            Name = "Handcrafted Soft Table",
                            Price = 309.11m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 45, 30, 142, DateTimeKind.Local).AddTicks(563)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 10, 28, 15, 2, 13, 809, DateTimeKind.Local).AddTicks(1584),
                            Description = "Exercitationem rerum cum qui sed quas assumenda.",
                            Name = "Tasty Cotton Chicken",
                            Price = 674.98m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 14, 48, 819, DateTimeKind.Local).AddTicks(3476)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 10, 28, 21, 25, 51, 791, DateTimeKind.Local).AddTicks(3950),
                            Description = "Et explicabo praesentium qui.",
                            Name = "Tasty Plastic Ball",
                            Price = 743.73m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 4, 34, 739, DateTimeKind.Local).AddTicks(3378)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 3, 3, 23, 43, 25, 283, DateTimeKind.Local).AddTicks(1393),
                            Description = "Inventore maxime expedita maiores esse dicta aliquid blanditiis magni.",
                            Name = "Intelligent Plastic Bike",
                            Price = 104.34m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 34, 58, 245, DateTimeKind.Local).AddTicks(2676)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 6, 23, 4, 53, 32, 601, DateTimeKind.Local).AddTicks(5624),
                            Description = "Fugiat dolorem quia fugit provident.",
                            Name = "Practical Fresh Towels",
                            Price = 186.76m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 34, 39, 410, DateTimeKind.Local).AddTicks(4370)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 7, 1, 16, 47, 9, 877, DateTimeKind.Local).AddTicks(292),
                            Description = "Beatae libero qui voluptates alias.",
                            Name = "Fantastic Soft Pizza",
                            Price = 550.61m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 10, 38, 278, DateTimeKind.Local).AddTicks(3814)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 8, 21, 4, 15, 33, 197, DateTimeKind.Local).AddTicks(7868),
                            Description = "Sint ullam enim minima magni assumenda tempora est dolorem pariatur.",
                            Name = "Practical Steel Hat",
                            Price = 701.91m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 24, 44, 750, DateTimeKind.Local).AddTicks(1403)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 11, 5, 3, 32, 37, 768, DateTimeKind.Local).AddTicks(7568),
                            Description = "Voluptatem laboriosam amet quisquam consequatur aut.",
                            Name = "Rustic Wooden Chips",
                            Price = 457.44m,
                            UpdatedAt = new DateTime(2025, 6, 2, 22, 54, 52, 605, DateTimeKind.Local).AddTicks(7997)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2025, 2, 21, 7, 48, 25, 86, DateTimeKind.Local).AddTicks(205),
                            Description = "Modi quae eum tempore incidunt nam blanditiis error a.",
                            Name = "Rustic Metal Hat",
                            Price = 798.84m,
                            UpdatedAt = new DateTime(2025, 6, 3, 0, 27, 28, 217, DateTimeKind.Local).AddTicks(4699)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2025, 2, 20, 4, 22, 57, 199, DateTimeKind.Local).AddTicks(9508),
                            Description = "Aut qui impedit id earum aliquid dolore sed.",
                            Name = "Ergonomic Fresh Gloves",
                            Price = 355.49m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 41, 55, 990, DateTimeKind.Local).AddTicks(1945)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2025, 1, 6, 6, 17, 14, 213, DateTimeKind.Local).AddTicks(3610),
                            Description = "Quae possimus saepe ut fuga quas quasi dolores.",
                            Name = "Refined Wooden Chicken",
                            Price = 108.95m,
                            UpdatedAt = new DateTime(2025, 6, 2, 15, 55, 4, 144, DateTimeKind.Local).AddTicks(4971)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 8, 6, 11, 19, 27, 283, DateTimeKind.Local).AddTicks(1115),
                            Description = "Praesentium velit possimus.",
                            Name = "Fantastic Steel Pants",
                            Price = 417.31m,
                            UpdatedAt = new DateTime(2025, 6, 2, 20, 43, 9, 400, DateTimeKind.Local).AddTicks(958)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 10, 13, 3, 16, 10, 462, DateTimeKind.Local).AddTicks(1068),
                            Description = "Facere quos et modi ipsum.",
                            Name = "Fantastic Soft Computer",
                            Price = 834.24m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 47, 49, 812, DateTimeKind.Local).AddTicks(2062)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 12, 6, 11, 32, 23, 443, DateTimeKind.Local).AddTicks(6884),
                            Description = "Id quisquam praesentium rerum et repellat consequatur vitae.",
                            Name = "Handmade Rubber Shoes",
                            Price = 488.44m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 27, 48, 970, DateTimeKind.Local).AddTicks(3165)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2025, 1, 3, 7, 25, 5, 98, DateTimeKind.Local).AddTicks(7826),
                            Description = "Recusandae vitae et.",
                            Name = "Fantastic Steel Towels",
                            Price = 76.69m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 46, 23, 213, DateTimeKind.Local).AddTicks(5940)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2025, 1, 31, 9, 5, 10, 969, DateTimeKind.Local).AddTicks(6262),
                            Description = "Cum dolorem soluta hic ducimus.",
                            Name = "Practical Fresh Keyboard",
                            Price = 431.66m,
                            UpdatedAt = new DateTime(2025, 6, 2, 11, 55, 31, 126, DateTimeKind.Local).AddTicks(9555)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2024, 9, 4, 9, 48, 36, 747, DateTimeKind.Local).AddTicks(7415),
                            Description = "Eveniet non odit cumque voluptatem.",
                            Name = "Handmade Fresh Pants",
                            Price = 160.97m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 42, 16, 571, DateTimeKind.Local).AddTicks(5086)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 12, 29, 22, 30, 5, 298, DateTimeKind.Local).AddTicks(9998),
                            Description = "Debitis aliquam corporis sed.",
                            Name = "Unbranded Concrete Mouse",
                            Price = 715.83m,
                            UpdatedAt = new DateTime(2025, 6, 3, 0, 28, 26, 787, DateTimeKind.Local).AddTicks(4890)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 7, 22, 10, 7, 54, 627, DateTimeKind.Local).AddTicks(6926),
                            Description = "Incidunt vel fugit.",
                            Name = "Handcrafted Plastic Hat",
                            Price = 909.44m,
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 1, 37, 270, DateTimeKind.Local).AddTicks(7208)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2024, 12, 25, 14, 57, 5, 34, DateTimeKind.Local).AddTicks(3356),
                            Description = "Consequatur in corrupti.",
                            Name = "Handmade Rubber Ball",
                            Price = 995.63m,
                            UpdatedAt = new DateTime(2025, 6, 2, 22, 7, 15, 651, DateTimeKind.Local).AddTicks(4289)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2024, 8, 2, 1, 58, 37, 273, DateTimeKind.Local).AddTicks(5941),
                            Description = "Minus non ratione.",
                            Name = "Refined Frozen Towels",
                            Price = 139.76m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 12, 51, 944, DateTimeKind.Local).AddTicks(4767)
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 10, 12, 17, 8, 59, 637, DateTimeKind.Local).AddTicks(1432),
                            Description = "Numquam quo ipsa odio sunt.",
                            Name = "Generic Fresh Sausages",
                            Price = 712.59m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 38, 17, 980, DateTimeKind.Local).AddTicks(6908)
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2025, 4, 15, 21, 33, 35, 396, DateTimeKind.Local).AddTicks(385),
                            Description = "Id perspiciatis asperiores omnis.",
                            Name = "Awesome Frozen Pants",
                            Price = 690.04m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 2, 43, 752, DateTimeKind.Local).AddTicks(4618)
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2025, 5, 2, 3, 44, 5, 264, DateTimeKind.Local).AddTicks(336),
                            Description = "Cupiditate velit sint aliquid et doloribus et.",
                            Name = "Intelligent Cotton Cheese",
                            Price = 256.10m,
                            UpdatedAt = new DateTime(2025, 6, 3, 4, 41, 45, 773, DateTimeKind.Local).AddTicks(8864)
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2025, 4, 14, 11, 33, 4, 487, DateTimeKind.Local).AddTicks(8035),
                            Description = "Magnam iusto doloribus culpa non accusantium.",
                            Name = "Rustic Frozen Fish",
                            Price = 898.83m,
                            UpdatedAt = new DateTime(2025, 6, 2, 11, 26, 9, 279, DateTimeKind.Local).AddTicks(2678)
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2025, 2, 4, 18, 35, 56, 892, DateTimeKind.Local).AddTicks(7316),
                            Description = "Ratione optio ut rerum molestias voluptatum mollitia.",
                            Name = "Gorgeous Plastic Shirt",
                            Price = 720.20m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 7, 32, 678, DateTimeKind.Local).AddTicks(9849)
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2024, 9, 28, 14, 14, 4, 794, DateTimeKind.Local).AddTicks(6230),
                            Description = "Aspernatur quis vel consectetur.",
                            Name = "Fantastic Steel Cheese",
                            Price = 632.16m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 40, 55, 974, DateTimeKind.Local).AddTicks(2065)
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 7, 27, 23, 59, 35, 463, DateTimeKind.Local).AddTicks(9851),
                            Description = "Tempore est consequatur ea aut ut ut.",
                            Name = "Awesome Steel Soap",
                            Price = 311.59m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 40, 4, 24, DateTimeKind.Local).AddTicks(126)
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2024, 7, 2, 2, 50, 42, 12, DateTimeKind.Local).AddTicks(7285),
                            Description = "Et praesentium odio.",
                            Name = "Practical Soft Hat",
                            Price = 829.07m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 46, 14, 990, DateTimeKind.Local).AddTicks(6781)
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2025, 1, 5, 8, 28, 47, 38, DateTimeKind.Local).AddTicks(3700),
                            Description = "Sint dicta aut.",
                            Name = "Rustic Cotton Gloves",
                            Price = 237.60m,
                            UpdatedAt = new DateTime(2025, 6, 3, 7, 13, 12, 833, DateTimeKind.Local).AddTicks(1251)
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2024, 7, 24, 8, 2, 23, 765, DateTimeKind.Local).AddTicks(4158),
                            Description = "Aut ex est et.",
                            Name = "Tasty Cotton Chips",
                            Price = 480.85m,
                            UpdatedAt = new DateTime(2025, 6, 3, 2, 23, 22, 672, DateTimeKind.Local).AddTicks(2560)
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2025, 1, 30, 3, 47, 3, 772, DateTimeKind.Local).AddTicks(2126),
                            Description = "Voluptas quia nulla iusto odio unde fugiat officiis est qui.",
                            Name = "Awesome Plastic Chips",
                            Price = 964.60m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 38, 1, 325, DateTimeKind.Local).AddTicks(2584)
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2025, 4, 4, 2, 53, 42, 640, DateTimeKind.Local).AddTicks(2408),
                            Description = "Laborum ut ut similique vero et reiciendis placeat.",
                            Name = "Small Granite Sausages",
                            Price = 586.95m,
                            UpdatedAt = new DateTime(2025, 6, 2, 16, 33, 14, 236, DateTimeKind.Local).AddTicks(9884)
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 8, 22, 4, 3, 22, 385, DateTimeKind.Local).AddTicks(774),
                            Description = "Ullam iure deleniti aliquam eos doloribus quis.",
                            Name = "Refined Steel Hat",
                            Price = 290.18m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 21, 14, 38, DateTimeKind.Local).AddTicks(4093)
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 6, 9, 15, 6, 23, 857, DateTimeKind.Local).AddTicks(6095),
                            Description = "Eum perferendis ut cumque quae reprehenderit.",
                            Name = "Gorgeous Rubber Soap",
                            Price = 604.40m,
                            UpdatedAt = new DateTime(2025, 6, 2, 14, 1, 5, 879, DateTimeKind.Local).AddTicks(6923)
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2024, 8, 1, 15, 46, 38, 524, DateTimeKind.Local).AddTicks(3083),
                            Description = "Sunt quas nulla.",
                            Name = "Gorgeous Plastic Hat",
                            Price = 741.35m,
                            UpdatedAt = new DateTime(2025, 6, 3, 1, 57, 14, 569, DateTimeKind.Local).AddTicks(8330)
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 10, 30, 22, 42, 6, 750, DateTimeKind.Local).AddTicks(6789),
                            Description = "Quia eum et nostrum culpa accusantium fugiat.",
                            Name = "Licensed Soft Salad",
                            Price = 514.07m,
                            UpdatedAt = new DateTime(2025, 6, 3, 0, 58, 15, 147, DateTimeKind.Local).AddTicks(4723)
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2025, 1, 3, 13, 45, 34, 820, DateTimeKind.Local).AddTicks(9986),
                            Description = "Vel aliquid nemo sunt dolore accusamus quo consectetur.",
                            Name = "Sleek Rubber Bike",
                            Price = 920.42m,
                            UpdatedAt = new DateTime(2025, 6, 2, 18, 53, 2, 175, DateTimeKind.Local).AddTicks(4457)
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 7, 16, 18, 27, 36, 683, DateTimeKind.Local).AddTicks(7570),
                            Description = "Cupiditate eligendi molestiae molestias nihil accusamus excepturi est.",
                            Name = "Sleek Plastic Soap",
                            Price = 966.50m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 29, 45, 571, DateTimeKind.Local).AddTicks(869)
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2025, 1, 9, 4, 26, 12, 317, DateTimeKind.Local).AddTicks(7011),
                            Description = "Voluptatem deleniti sit qui est et minima qui voluptas.",
                            Name = "Unbranded Granite Bacon",
                            Price = 48.87m,
                            UpdatedAt = new DateTime(2025, 6, 2, 13, 7, 27, 767, DateTimeKind.Local).AddTicks(5067)
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 8, 16, 9, 12, 41, 700, DateTimeKind.Local).AddTicks(9805),
                            Description = "Ullam libero recusandae quo quod tenetur illum placeat.",
                            Name = "Generic Cotton Bacon",
                            Price = 61.47m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 22, 17, 250, DateTimeKind.Local).AddTicks(3518)
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2024, 10, 19, 5, 48, 21, 732, DateTimeKind.Local).AddTicks(7269),
                            Description = "Aut nihil animi nostrum expedita pariatur rerum.",
                            Name = "Unbranded Fresh Cheese",
                            Price = 817.99m,
                            UpdatedAt = new DateTime(2025, 6, 2, 17, 46, 51, 688, DateTimeKind.Local).AddTicks(5371)
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2025, 3, 30, 14, 33, 15, 11, DateTimeKind.Local).AddTicks(9550),
                            Description = "Sed labore repellendus voluptatem.",
                            Name = "Unbranded Granite Shoes",
                            Price = 113.36m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 27, 32, 38, DateTimeKind.Local).AddTicks(7702)
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2024, 10, 31, 9, 45, 37, 481, DateTimeKind.Local).AddTicks(6844),
                            Description = "Nihil ratione voluptatem ex perferendis doloribus ut.",
                            Name = "Generic Cotton Pizza",
                            Price = 591.11m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 35, 18, 119, DateTimeKind.Local).AddTicks(6393)
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2025, 5, 26, 22, 49, 16, 43, DateTimeKind.Local).AddTicks(3757),
                            Description = "Est recusandae a modi omnis deleniti quia quia.",
                            Name = "Small Granite Soap",
                            Price = 762.36m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 7, 0, 67, DateTimeKind.Local).AddTicks(9971)
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2024, 9, 3, 12, 3, 52, 226, DateTimeKind.Local).AddTicks(1781),
                            Description = "Quaerat accusantium consectetur consequatur nobis aut ducimus molestiae.",
                            Name = "Rustic Rubber Tuna",
                            Price = 135.42m,
                            UpdatedAt = new DateTime(2025, 6, 2, 19, 45, 1, 209, DateTimeKind.Local).AddTicks(2392)
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2024, 6, 5, 8, 57, 18, 362, DateTimeKind.Local).AddTicks(928),
                            Description = "Dolor sit aut omnis eum facere voluptate aut.",
                            Name = "Generic Granite Towels",
                            Price = 968.88m,
                            UpdatedAt = new DateTime(2025, 6, 3, 3, 51, 0, 128, DateTimeKind.Local).AddTicks(9779)
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2025, 5, 26, 12, 31, 37, 388, DateTimeKind.Local).AddTicks(3907),
                            Description = "Amet atque atque labore aut iste eos iusto officiis fugiat.",
                            Name = "Intelligent Frozen Chicken",
                            Price = 408.13m,
                            UpdatedAt = new DateTime(2025, 6, 3, 10, 37, 57, 820, DateTimeKind.Local).AddTicks(8100)
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2024, 11, 6, 18, 54, 46, 389, DateTimeKind.Local).AddTicks(5376),
                            Description = "Delectus ut adipisci consectetur possimus.",
                            Name = "Fantastic Frozen Shirt",
                            Price = 560.97m,
                            UpdatedAt = new DateTime(2025, 6, 2, 12, 26, 52, 963, DateTimeKind.Local).AddTicks(9309)
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2024, 12, 16, 11, 57, 30, 941, DateTimeKind.Local).AddTicks(5273),
                            Description = "Occaecati possimus porro enim quod debitis est.",
                            Name = "Generic Concrete Table",
                            Price = 526.16m,
                            UpdatedAt = new DateTime(2025, 6, 3, 5, 57, 12, 719, DateTimeKind.Local).AddTicks(9327)
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2024, 7, 13, 3, 0, 38, 694, DateTimeKind.Local).AddTicks(3164),
                            Description = "Excepturi reprehenderit temporibus praesentium unde hic.",
                            Name = "Unbranded Steel Chips",
                            Price = 440.33m,
                            UpdatedAt = new DateTime(2025, 6, 3, 8, 58, 48, 85, DateTimeKind.Local).AddTicks(275)
                        });
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TemplateFramework.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TemplateFramework.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
